ADC Driver
Analog-to-Digital Converter Library.
Files
file adc.h
Analog-to-Digital Converter API Header.
file adc.c
Analog-to-Digital Converter API Implementation.
Enumerations
enum ADCRef { AREF,
AVCC,
AINT1,
AINT2
 }
ADC Reference Voltage options.
Functions
void adcInit (ADCRef ref)
Initialize the ADC Hardware.
void adcStart (uint8_t channel)
Start a conversion on a given channel.
uint8_t adcReady (void)
Check if a result is ready.
uint16_t adcGet (uint8_t next)
Get the conversion results.
void adcClose (void)
Disable the ADC to save energy.
Detailed Description
Analog-to-Digital Converter Library. With 10bit Output and selectable Reference Voltage.
Enumeration Type Documentation
enum ADCRef
ADC Reference Voltage options.
Enumerator
AREF
 External Reference Voltage.
AVCC
 Supply Voltage.
AINT1
 Internal Reference 1 (1.1V)
AINT2
 Internal Reference 2 (2.56V)
Definition at line 45 of file adc.h.
             {
    AREF,
    AVCC,
    AINT1,
    AINT2
} ADCRef;
Function Documentation
void adcClose (void)
Disable the ADC to save energy.
Definition at line 107 of file adc.c.
                {
    // deactivate adc
    ADCSRA &= ~(1 << ADSC);
    PRR0 |= (1 << PRADC);
    ADCSRA &= ~(1 << ADEN);
}
uint16_t adcGet (uint8_t next)
Get the conversion results.
Parameters
next Start next conversion if != 0
Returns
10bit ADC value
Definition at line 96 of file adc.c.
References adcReady().
Referenced by getVoltage().
                              {
    // Return measurements result
    // Start next conversion
    uint16_t temp = 0;
    while (!adcReady());
    temp = ADC;
    if (next)
        ADCSRA |= (1 << ADSC); // Start next conversion
    return temp;
}
void adcInit (ADCRef ref)
Initialize the ADC Hardware.
Parameters
ref Reference Voltage.
Definition at line 44 of file adc.c.
References AINT1, AINT2, AREF, and AVCC.
Referenced by xyInit().
                         {
    // Enable ADC Module, start one conversion, wait for finish
    PRR0 &= ~(1 << PRADC); // Disable ADC Power Reduction (Enable it...)
    switch(ref) {
        case AVCC:
            ADMUX = (1 << REFS0);
            break;
        case AINT1:
            ADMUX = (1 << REFS1);
            break;
        case AINT2:
            ADMUX = (1 << REFS1) | (1 << REFS0);
            break;
        case AREF:
            ADMUX &= ~((1 << REFS0) | (1 << REFS1));
            break;
    }
    ADCSRA = (1 << ADPS2) | (1 << ADPS1) | (1 << ADPS0); // Prescaler 128
    ADCSRB = 0;
    ADCSRA |= (1 << ADEN) | (1 << ADSC); // Start ADC, single conversion
}
uint8_t adcReady (void)
Check if a result is ready.
Returns
1 if conversion is done.
Definition at line 86 of file adc.c.
Referenced by adcGet(), and getVoltage().
                   {
    // Is the measurement finished
    if (ADCSRA & (1 << ADSC)) {
        // ADSC bit is set
        return 0;
    } else {
        return 1;
    }
}
void adcStart (uint8_t channel)
Start a conversion on a given channel.
Parameters
channel Channel (0 - 15)
Definition at line 70 of file adc.c.
Referenced by getVoltage().
                               {
    // Start a measurement on channel
    if (channel > 15) {
        channel = 0;
    }
    if (channel > 7) {
        channel -= 8;
        ADCSRB |= (1 << MUX5);
    } else {
        ADCSRB &= ~(1 << MUX5);
    }
    ADMUX &= ~0x1F; // Delete MUX0:4
    ADMUX |= channel;
    ADCSRA |= (1 << ADSC);
}