Accelerometer Driver
Configuring and reading an LSM303DLHC Accelerometer.
Files
file acc.h
LSM303DLHC Accelerometer API Header.
file acc.c
LSM303DLHC Accelerometer API Implementation.
Macros
#define ACC_ADDRESS 0x32
Accelerometer Address (0011001r)
#define ACCFILTERFACTOR 1
Accelerometer Low Pass Factor.
#define ACCREG_CTRL1 0x20
Accelerometer Control Register 1.
#define ACCREG_CTRL4 0x23
Accelerometer Control Register 4.
#define ACCREG_XL 0x28
First Accelerometer Output Register.
Enumerations
enum AccRange { r2G,
r4G,
r8G,
r16G
 }
Accelerometer Range options.
Functions
Error accInit (AccRange r)
Initialize the Accelerometer.
Error accRead (Vector3f *v)
Read from the Accelerometer.
Error accWriteRegister (uint8_t reg, uint8_t val)
Write an Accelerometer Register.
Variables
AccRange accRange
Stored range to scale returned values.
Detailed Description
Configuring and reading an LSM303DLHC Accelerometer.
Macro Definition Documentation
#define ACC_ADDRESS 0x32
Accelerometer Address (0011001r)
Definition at line 46 of file acc.h.
Referenced by accRead().
#define ACCFILTERFACTOR 1
Accelerometer Low Pass Factor.
Definition at line 49 of file acc.h.
Referenced by accRead().
#define ACCREG_CTRL1 0x20
Accelerometer Control Register 1.
Definition at line 47 of file acc.c.
Referenced by accInit().
#define ACCREG_CTRL4 0x23
Accelerometer Control Register 4.
Definition at line 48 of file acc.c.
Referenced by accInit().
#define ACCREG_XL 0x28
First Accelerometer Output Register.
Definition at line 49 of file acc.c.
Referenced by accRead().
Enumeration Type Documentation
enum AccRange
Accelerometer Range options.
Enumerator
r2G
 +- 2G
r4G
 +- 4G
r8G
 +- 8G
r16G
 +- 16G
Definition at line 52 of file acc.h.
             {
    r2G,
    r4G,
    r8G,
    r16G,
} AccRange;
Function Documentation
Error accInit (AccRange r)
Initialize the Accelerometer.
Call before accRead(). I2C should already be initialized!
Parameters
r AccRange to use.
Returns
TWI_NO_ANSWER, TWI_WRITE_ERROR, ARGUMENT_ERROR or SUCCESS.
Examples:
flight.c.
Definition at line 74 of file acc.c.
References accRange, ACCREG_CTRL1, ACCREG_CTRL4, accWriteRegister(), ARGUMENT_ERROR, r16G, r2G, r4G, r8G, and SUCCESS.
                          {
    uint8_t v;
    switch (r) {
        case r2G:
            v = 0x00;
            break;
        case r4G:
            v = 0x10;
            break;
        case r8G:
            v = 0x20;
            break;
        case r16G:
            v = 0x30;
            break;
        default:
            return ARGUMENT_ERROR;
    }
    accRange = r;
    Error e = accWriteRegister(ACCREG_CTRL1, 0x57); // Enable all axes,
       100Hz
    if (e != SUCCESS) {
        return e;
    }
    e = accWriteRegister(ACCREG_CTRL4, v);
    return e;
}
Error accRead (Vector3f * v)
Read from the Accelerometer.
Accelerometer should already be initialized!
Parameters
v Vector3f for the read values
Returns
TWI_NO_ANSWER, TWI_WRITE_ERROR, ARGUMENT_ERROR or SUCCESS.
Definition at line 101 of file acc.c.
References ACC_ADDRESS, ACCFILTERFACTOR, accRange, ACCREG_XL, ARGUMENT_ERROR, r16G, r2G, r4G, r8G, SUCCESS, TWI_NO_ANSWER, TWI_READ, TWI_WRITE, TWI_WRITE_ERROR, twiReadAck(), twiReadNak(), twiRepStart(), twiStart(), twiWrite(), Vector3f::x, Vector3f::y, and Vector3f::z.
                           {
    static double accSumX = 0; /* Buffer for X Low-Pass. */
    static double accSumY = 0; /* Buffer for Y Low-Pass. */
    static double accSumZ = 0; /* Buffer for Z Low-Pass. */
    static double accFilterX = 0; /* Buffer for X Low-Pass. */
    static double accFilterY = 0; /* Buffer for Y Low-Pass. */
    static double accFilterZ = 0; /* Buffer for Z Low-Pass. */
    if (v == NULL) {
        return ARGUMENT_ERROR;
    }
    if (twiStart(ACC_ADDRESS | TWI_WRITE)) {
        return TWI_NO_ANSWER;
    }
    if (twiWrite(ACCREG_XL | (1 << 7))) { // Auto Increment
        return TWI_WRITE_ERROR;
    }
    if (twiRepStart(ACC_ADDRESS | TWI_READ)) {
        return TWI_NO_ANSWER;
    }
    uint8_t xl = twiReadAck();
    uint8_t xh = twiReadAck();
    uint8_t yl = twiReadAck();
    uint8_t yh = twiReadAck();
    uint8_t zl = twiReadAck();
    uint8_t zh = twiReadNak();
    int16_t x = *(int8_t *)(&xh);
    x *= (1 << 8);
    x |= xl;
    int16_t y = *(int8_t *)(&yh);
    y *= (1 << 8);
    y |= yl;
    int16_t z = *(int8_t *)(&zh);
    z *= (1 << 8);
    z |= zl;
    switch (accRange) {
        case r2G:
            v->x = (((double)x) * 2 / 0x8000);
            v->y = (((double)y) * 2 / 0x8000);
            v->z = (((double)z) * 2 / 0x8000);
            break;
        case r4G:
            v->x = (((double)x) * 4 / 0x8000);
            v->y = (((double)y) * 4 / 0x8000);
            v->z = (((double)z) * 4 / 0x8000);
            break;
        case r8G:
            v->x = (((double)x) * 8 / 0x8000);
            v->y = (((double)y) * 8 / 0x8000);
            v->z = (((double)z) * 8 / 0x8000);
            break;
        case r16G:
            v->x = (((double)x) * 16 / 0x8000);
            v->y = (((double)y) * 16 / 0x8000);
            v->z = (((double)z) * 16 / 0x8000);
            break;
        default:
            return ARGUMENT_ERROR;
    }
    accSumX = accSumX - accFilterX + v->x;
    accFilterX = accSumX / ACCFILTERFACTOR;
    v->x = accFilterX;
    accSumY = accSumY - accFilterY + v->y;
    accFilterY = accSumY / ACCFILTERFACTOR;
    v->y = accFilterY;
    accSumZ = accSumZ - accFilterZ + v->z;
    accFilterZ = accSumZ / ACCFILTERFACTOR;
    v->z = accFilterZ;
    return SUCCESS;
}
Error accWriteRegister (uint8_t reg, uint8_t val)
Write an Accelerometer Register.
I2C should aready be initialized!
Parameters
reg Register Address
val New Value
Returns
TWI_NO_ANSWER, TWI_WRITE_ERROR or SUCCESS.
Definition at line 60 of file acc.c.
References TWI_NO_ANSWER.
Referenced by accInit().
                                                 {
    if (twiStart(ACC_ADDRESS | TWI_WRITE)) {
        return TWI_NO_ANSWER;
    }
    if (twiWrite(reg)) {
        return TWI_WRITE_ERROR;
    }
    if (twiWrite(val)) {
        return TWI_WRITE_ERROR;
    }
    twiStop();
    return SUCCESS;
}
Variable Documentation
AccRange accRange
Stored range to scale returned values.
Definition at line 51 of file acc.c.
Referenced by accInit(), and accRead().