Complementary-Filter
Complementary-Filter.
Files
file complementary.h
Complementary-Filter Header.
file complementary.c
Complementary-Filter Implementation.
Data Structures
struct Complementary
Cmplementary-Filter State data.
Functions
void complementaryExecute (Complementary *data, double acc, double gyro)
Step the Complementary Filter.
void complementaryInit (Complementary *data)
Initialize a Complementary-State.
Detailed Description
Complementary-Filter. Inspired by this presentation...
Function Documentation
void complementaryExecute (Complementary * data, double acc, double gyro)
Step the Complementary Filter.
Parameters
data Complementary-Filter State
acc Angle from Accelerometer
gyro Corresponding Gyroscope data
Definition at line 50 of file complementary.c.
References COMPLEMENTARY_TAU, and getSystemTime().
Referenced by orientationTask().
                                                                        {
    time_t dtInteger = (getSystemTime() - data->lastExecute);
    double dt = dtInteger / 1000;
    data->angle = (data->angle + (gyro * dt)); // Gyro Integrator
    data->angle *= COMPLEMENTARY_TAU / (COMPLEMENTARY_TAU + dt); //
       High-Pass
    data->angle += (1 - (COMPLEMENTARY_TAU / (COMPLEMENTARY_TAU + dt))) *
       acc; // Low-Pass
    data->lastExecute = getSystemTime();
}
void complementaryInit (Complementary * data)
Initialize a Complementary-State.
Parameters
data Complementary-State to be initialized
Definition at line 45 of file complementary.c.
References getSystemTime().
Referenced by orientationInit().
                                            {
    data->angle = 0;
    data->lastExecute = getSystemTime();
}