Motor Controller Driver
Controlling four BL-Ctrl V1.2 Brushless controllers.
Files
file motor.h
BL-Ctrl V1.2 Controller API Header.
file motor.c
BL-Ctrl V1.2 Controller API Implementation.
Functions
void motorInit (void)
Initializes the motor control library.
void motorSet (uint8_t id, uint8_t speed)
Set the speed of one or all motors.
void motorTask (void)
Send the values stored in motorSpeed to the Controllers.
Variables
uint8_t motorSpeed [MOTORCOUNT]
Speed for the four motors.
uint8_t motorSpeed [MOTORCOUNT]
Speed for the four motors.
Detailed Description
Controlling four BL-Ctrl V1.2 Brushless controllers.
Function Documentation
void motorInit (void)
Initializes the motor control library.
Really only sets motorSpeed to zero.
Examples:
uartFlight.c.
Definition at line 58 of file motor.c.
References MOTORCOUNT, and motorSpeed.
                     {
    for (uint8_t i = 0; i < MOTORCOUNT; i++) {
        motorSpeed[i] = 0;
    }
}
void motorSet (uint8_t id, uint8_t speed)
Set the speed of one or all motors.
Parameters
id Motor ID (0 to 3, 4 = all)
speed New Speed
Definition at line 64 of file motor.c.
References MOTORCOUNT, and motorSpeed.
Referenced by setMotorSpeeds().
                                         {
    if (id < MOTORCOUNT) {
        motorSpeed[id] = speed;
    } else {
        for (id = 0; id < MOTORCOUNT; id++) {
            motorSpeed[id] = speed;
        }
    }
}
void motorTask (void)
Send the values stored in motorSpeed to the Controllers.
I2C already has to be initialized!
Examples:
uartFlight.c.
Definition at line 50 of file motor.c.
References MOTOR_BASEADDRESS, MOTORCOUNT, motorSpeed, TWI_WRITE, twiStart(), twiStop(), and twiWrite().
                     {
    for (uint8_t i = 0; i < MOTORCOUNT; i++) {
        twiStart(MOTOR_BASEADDRESS + (i << 1) +
      TWI_WRITE);
        twiWrite(motorSpeed[i]);
        twiStop();
    }
}
Variable Documentation
uint8_t motorSpeed[MOTORCOUNT]
Speed for the four motors.
Examples:
uartFlight.c.
Definition at line 48 of file motor.c.
Referenced by motorInit(), motorSet(), and motorTask().
uint8_t motorSpeed[MOTORCOUNT]
Speed for the four motors.
Definition at line 48 of file motor.c.
Referenced by motorInit(), motorSet(), and motorTask().