xyControl Hardware
Controls xyControl On-Board Hardware like LEDs.
Files
file xycontrol.h
xyControl API Header.
file xycontrol.c
xyControl API Implementation.
Data Structures
struct Vector3f
The global 3-Dimensional Floating Point Vector.
Enumerations
enum LED {
*
LED_RED0 = 0,
LED_RED1 = 1,
LED_GREEN0 = 2,
LED_GREEN1 = 3,
*
LED_ALL = 4,
LED_BITMAP = 5,
LED_RED = 6,
LED_GREEN = 7
 }
Methods of addressing the LEDs.
enum LEDState { LED_OFF = 0,
LED_ON = 1,
LED_TOGGLE = 2
 }
Possible states of the LEDs.
Functions
void xyInit (void)
Initialize the xyControl Hardware.
void xyLed (LED l, LEDState v)
Set the LEDs.
double getVoltage (void)
Calculate and return the Battery Voltage.
void xySelfReset (void)
Use the Watchdog to reset yourself after 15ms.
int64_t map (int64_t value, int64_t oldMin, int64_t oldMax, int64_t newMin, int64_t newMax)
Map an Integer from one range to another range.
int uartoutput (char c, FILE *f)
Method used to write to stdout and stderr.
int uartinput (FILE *f)
Method used to read from stdin.
void xyLedInternal (uint8_t v, volatile uint8_t *port, uint8_t pin)
Internal LED Manipulation function.
Variables
char PROGMEM helpText [] = `Print this Help`
UART Menu Help Text.
char PROGMEM resetText [] = `Reset MCU`
UART Menu Reset Text.
FILE inFile
FILE for stdin.
FILE outFile
FILE for stdout and stderr.
Detailed Description
Controls xyControl On-Board Hardware like LEDs.
Enumeration Type Documentation
enum LED
Methods of addressing the LEDs.
Enumerator
LED_RED0
 First red LED.
LED_RED1
 Second red LED.
LED_GREEN0
 First green LED.
LED_GREEN1
 Second green LED.
LED_ALL
 All LEDs.
LED_BITMAP
 LEDs as Bitmap (R0, R1, G0, G1)
LED_RED
 Both red LEDs.
LED_GREEN
 Both green LEDs.
Definition at line 44 of file xycontrol.h.
             {
    LED_RED0 = 0,
    LED_RED1 = 1,
    LED_GREEN0 = 2,
    LED_GREEN1 = 3,
    LED_ALL = 4,
    LED_BITMAP = 5,
    LED_RED = 6,
    LED_GREEN = 7
} LED;
enum LEDState
Possible states of the LEDs.
Enumerator
LED_OFF
 LED Off.
LED_ON
 LED On.
LED_TOGGLE
 Toggle the LED.
Definition at line 56 of file xycontrol.h.
             {
    LED_OFF = 0,
    LED_ON = 1,
    LED_TOGGLE = 2
} LEDState;
Function Documentation
double getVoltage (void)
Calculate and return the Battery Voltage.
Returns
Current Battery Voltage
Examples:
hardwareTest.c, and uartFlight.c.
Definition at line 172 of file xycontrol.c.
References adcGet(), adcReady(), adcStart(), BATT_CHANNEL, and BATT_MAX.
                        {
    adcStart(BATT_CHANNEL);
    while(!adcReady());
    uint16_t v = adcGet(0) * BATT_MAX;
    return ((double)v / 1024.0);
}
int64_t map (int64_t value, int64_t oldMin, int64_t oldMax, int64_t newMin, int64_t newMax)
Map an Integer from one range to another range.
Parameters
value Integer to operate on
oldMin Lower Limit of Input range
oldMax Upper Limit of Input range
newMin Lower Limit of Output range
newMax Upper Limit of Output range
Returns
Value in new range
Definition at line 184 of file xycontrol.c.
                                                                                           {
    return (value - oldMin) * (newMax - newMin) / (oldMax - oldMin) + newMin;
}
int uartinput (FILE * f)
Method used to read from stdin.
Definition at line 81 of file xycontrol.c.
References serialAvailable(), serialGet(), and serialHasChar().
Referenced by xyInit().
                       {
    for (;;) {
        for (uint8_t i = 0; i < serialAvailable(); i++) {
            if (serialHasChar(i)) {
                return serialGet(i);
            }
        }
    }
}
int uartoutput (char c, FILE * f)
Method used to write to stdout and stderr.
Definition at line 66 of file xycontrol.c.
References serialAvailable(), and serialWrite().
Referenced by xyInit().
                                {
    // Inject CR here, instead of in the serial library,
    // so we can still do binary transfers with serialWrite()...
    if (c == '\n') {
        for (uint8_t i = 0; i < serialAvailable(); i++)
            serialWrite(i, '\r');
    }
    if (c != '\r') {
        for (uint8_t i = 0; i < serialAvailable(); i++)
            serialWrite(i, c);
    }
    return 0;
}
void xyInit (void)
Initialize the xyControl Hardware.
Initializes LEDs, Timer, UART, I2C, SPI, ADC, the UART Menu and prepares stdin and stdout.
Examples:
hardwareTest.c, test.c, and uartFlight.c.
Definition at line 91 of file xycontrol.c.
References adcInit(), addMenuCommand(), addTask(), AVCC, BAUD, helpText, inFile, initSystemTimer(), LED0DDR, LED0PIN, LED1DDR, LED1PIN, LED2DDR, LED2PIN, LED3DDR, LED3PIN, MODE_0, outFile, resetText, serialAvailable(), serialInit(), SPEED_2, spiInit(), twiInit(), uartinput(), uartMenuPrintHelp(), uartMenuTask(), uartoutput(), xmemInit(), xyLed(), and xySelfReset().
                  {
    xmemInit(); // Most important!
    // LEDs
    LED0DDR |= (1 << LED0PIN);
    LED1DDR |= (1 << LED1PIN);
    LED2DDR |= (1 << LED2PIN);
    LED3DDR |= (1 << LED3PIN);
    xyLed(4, 1);
    initSystemTimer();
    for (uint8_t i = 0; i < serialAvailable(); i++) {
        serialInit(i, BAUD(38400, F_CPU));
    }
    twiInit();
    spiInit(MODE_0, SPEED_2);
    adcInit(AVCC);
    addMenuCommand('q', resetText, &xySelfReset);
    addMenuCommand('h', helpText, &uartMenuPrintHelp);
    addTask(&uartMenuTask);
    // fdevopen() is using malloc, so printf in a different
    // memory bank will not work!
    // fdevopen(&uartoutput, NULL); // stdout & stderr
    // fdevopen(NULL, &uartinput); // stdin
    // Instead we have the FILE structs as static variables
    // and assign them to stdin, stdout and stderr
    fdev_setup_stream(&outFile, &uartoutput, NULL, _FDEV_SETUP_WRITE);
    fdev_setup_stream(&inFile, NULL, &uartinput, _FDEV_SETUP_READ);
    stdin = &inFile;
    stdout = &outFile;
    stderr = &outFile;
    sei();
}
void xyLed (LED l, LEDState v)
Set the LEDs.
Parameters
l LEDs to set
v New LED State
Examples:
hardwareTest.c, test.c, and uartFlight.c.
Referenced by xyInit().
void xyLedInternal (uint8_t v, volatile uint8_t * port, uint8_t pin)
Internal LED Manipulation function.
Parameters
v New LED State (Off, On, Toggle)
port The Corresponding Output Port
pin The LED Pin
Definition at line 134 of file xycontrol.c.
                                                                   {
    if (v == 0) {
        *port &= ~(1 << pin);
    } else if (v == 1) {
        *port |= (1 << pin);
    } else {
        *port ^= (1 << pin);
    }
}
void xySelfReset (void)
Use the Watchdog to reset yourself after 15ms.
Definition at line 179 of file xycontrol.c.
Referenced by orientationTask(), and xyInit().
                       {
    wdt_enable(WDTO_15MS);
    for(;;);
}
Variable Documentation
char PROGMEM helpText[] = `Print this Help`
UART Menu Help Text.
Definition at line 59 of file xycontrol.c.
Referenced by xyInit().
FILE inFile
FILE for stdin.
Definition at line 62 of file xycontrol.c.
Referenced by xyInit().
FILE outFile
FILE for stdout and stderr.
Definition at line 63 of file xycontrol.c.
Referenced by xyInit().
char PROGMEM resetText[] = `Reset MCU`
UART Menu Reset Text.
Definition at line 60 of file xycontrol.c.
Referenced by xyInit().