UART Library
UART Library enabling you to control all available UART Modules.
Files
file serial.h
UART Library Header File.
file serial_device.h
UART Library device-specific configuration.
file serial.c
UART Library Implementation.
Macros
#define USB 0
First UART Name.
#define DISPLAY 1
Second UART Name.
#define RX_BUFFER_SIZE 128
UART Receive Buffer Size.
#define TX_BUFFER_SIZE 128
UART Transmit Buffer Size.
#define BAUD(baudRate, xtalCpu) ((xtalCpu)/((baudRate)*16l)-1)
Calculate Baudrate Register Value.
#define RX_BUFFER_SIZE 32
If you define this, a '\r' (CR) will be put in front of a '\n' (LF) when sending a byte.
#define TX_BUFFER_SIZE 16
TX Buffer Size in Bytes (Power of 2)
#define FLOWCONTROL
Defining this enables incoming XON XOFF (sends XOFF if rx buff is full)
#define FLOWMARK 5
Space remaining to trigger xoff/xon.
#define XON 0x11
XON Value.
#define XOFF 0x13
XOFF Value.
Functions
uint8_t serialAvailable (void)
Get number of available UART modules.
uint8_t serialInit (uint8_t uart, uint16_t baud)
Initialize the UART Hardware.
void serialClose (uint8_t uart)
Stop the UART Hardware.
void setFlow (uint8_t uart, uint8_t on)
Manually change the flow control.
uint8_t serialHasChar (uint8_t uart)
Check if a byte was received.
uint8_t serialGet (uint8_t uart)
Read a single byte.
uint8_t serialGetBlocking (uint8_t uart)
Wait until a character is received.
uint8_t serialRxBufferFull (uint8_t uart)
Check if the receive buffer is full.
uint8_t serialRxBufferEmpty (uint8_t uart)
Check if the receive buffer is empty.
void serialWrite (uint8_t uart, uint8_t data)
Send a byte.
void serialWriteString (uint8_t uart, const char *data)
Send a string.
uint8_t serialTxBufferFull (uint8_t uart)
Check if the transmit buffer is full.
uint8_t serialTxBufferEmpty (uint8_t uart)
Check if the transmit buffer is empty.
Detailed Description
UART Library enabling you to control all available UART Modules. With XON/XOFF Flow Control and buffered Receiving and Transmitting.
Macro Definition Documentation
#define BAUD(baudRate, xtalCpu) ((xtalCpu)/((baudRate)*16l)-1)
Calculate Baudrate Register Value.
Examples:
flight.c.
Definition at line 52 of file serial.h.
#define DISPLAY 1
Second UART Name.
Definition at line 46 of file serial.h.
#define FLOWCONTROL
Defining this enables incoming XON XOFF (sends XOFF if rx buff is full)
Definition at line 64 of file serial.c.
#define FLOWMARK 5
Space remaining to trigger xoff/xon.
Definition at line 66 of file serial.c.
Referenced by serialGet().
#define RX_BUFFER_SIZE 128
UART Receive Buffer Size.
Definition at line 48 of file serial.h.
#define RX_BUFFER_SIZE 32
If you define this, a '\r' (CR) will be put in front of a '\n' (LF) when sending a byte.
Binary Communication will then be impossible!RX Buffer Size in Bytes (Power of 2)
Definition at line 56 of file serial.c.
Referenced by serialGet(), serialInit(), and serialRxBufferFull().
#define TX_BUFFER_SIZE 128
UART Transmit Buffer Size.
Definition at line 49 of file serial.h.
#define TX_BUFFER_SIZE 16
TX Buffer Size in Bytes (Power of 2)
Definition at line 60 of file serial.c.
Referenced by serialInit(), serialTxBufferFull(), and serialWrite().
#define USB 0
First UART Name.
Definition at line 45 of file serial.h.
#define XOFF 0x13
XOFF Value.
Definition at line 68 of file serial.c.
Referenced by setFlow().
#define XON 0x11
XON Value.
Definition at line 67 of file serial.c.
Referenced by serialGet(), and setFlow().
Function Documentation
uint8_t serialAvailable (void)
Get number of available UART modules.
Returns
number of modules
Definition at line 115 of file serial.c.
                              {
    return UART_COUNT;
}
void serialClose (uint8_t uart)
Stop the UART Hardware.
Parameters
uart UART Module to stop
Definition at line 172 of file serial.c.
References BANK_SERIAL, MEMSWITCH, MEMSWITCHBACK, and serialTxBufferEmpty().
                               {
    if (uart >= UART_COUNT)
        return;
    MEMSWITCH(BANK_SERIAL);
    uint8_t sreg = SREG;
    sei();
    while (!serialTxBufferEmpty(uart));
    while (*serialRegisters[uart][SERIALB] & (1 << serialBits[uart][SERIALUDRIE])); // Wait while Transmit
       Interrupt is on
    cli();
    *serialRegisters[uart][SERIALB] = 0;
    *serialRegisters[uart][SERIALC] = 0;
    SREG = sreg;
    free(rxBuffer[uart]);
    free(txBuffer[uart]);
    MEMSWITCHBACK(BANK_SERIAL);
}
uint8_t serialGet (uint8_t uart)
Read a single byte.
Parameters
uart UART Module to read from
Returns
Received byte or 0
Definition at line 245 of file serial.c.
References BANK_SERIAL, FLOWMARK, MEMSWITCH, MEMSWITCHBACK, RX_BUFFER_SIZE, and XON.
Referenced by serialGetBlocking().
                                {
    if (uart >= UART_COUNT)
        return 0;
    uint8_t c;
    MEMSWITCH(BANK_SERIAL);
#ifdef FLOWCONTROL
    rxBufferElements[uart]--;
    if ((flow[uart] == 0) && (rxBufferElements[uart] <= FLOWMARK)) {
        while (sendThisNext[uart] != 0);
        sendThisNext[uart] = XON;
        flow[uart] = 1;
        if (shouldStartTransmission[uart]) {
            shouldStartTransmission[uart] = 0;
            *serialRegisters[uart][SERIALB] |= (1 << serialBits[uart][SERIALUDRIE]); // Enable Interrupt
            *serialRegisters[uart][SERIALA] |= (1 << serialBits[uart][SERIALUDRE]); // Trigger Interrupt
        }
    }
#endif
    if (rxRead[uart] != rxWrite[uart]) {
        c = rxBuffer[uart][rxRead[uart]];
        rxBuffer[uart][rxRead[uart]] = 0;
        if (rxRead[uart] < (RX_BUFFER_SIZE - 1)) {
            rxRead[uart]++;
        } else {
            rxRead[uart] = 0;
        }
        MEMSWITCHBACK(BANK_SERIAL);
        return c;
    } else {
        MEMSWITCHBACK(BANK_SERIAL);
        return 0;
    }
}
uint8_t serialGetBlocking (uint8_t uart)
Wait until a character is received.
Parameters
uart UART Module to read from
Returns
Received byte
Definition at line 237 of file serial.c.
References serialGet(), and serialHasChar().
                                        {
    if (uart >= UART_COUNT)
        return 0;
    while(!serialHasChar(uart));
    return serialGet(uart);
}
uint8_t serialHasChar (uint8_t uart)
Check if a byte was received.
Parameters
uart UART Module to check
Returns
1 if a byte was received, 0 if not
Definition at line 226 of file serial.c.
Referenced by serialGetBlocking().
                                    {
    if (uart >= UART_COUNT)
        return 0;
    if (rxRead[uart] != rxWrite[uart]) { // True if char available
        return 1;
    } else {
        return 0;
    }
}
uint8_t serialInit (uint8_t uart, uint16_t baud)
Initialize the UART Hardware.
Parameters
uart UART Module to initialize
baud Baudrate. Use the BAUD() macro!
Returns
1 if not enough memory for buffers, 0 on success
Examples:
flight.c.
Definition at line 119 of file serial.c.
References BANK_SERIAL, MEMSWITCH, MEMSWITCHBACK, RX_BUFFER_SIZE, and TX_BUFFER_SIZE.
                                                {
    if (uart >= UART_COUNT) {
        for (uint8_t i = 0; i < UART_COUNT; i++) {
            serialInit(i, baud);
        }
    }
    MEMSWITCH(BANK_SERIAL);
    rxBuffer[uart] = (uint8_t *)malloc(RX_BUFFER_SIZE);
    if (rxBuffer[uart] == NULL) {
        MEMSWITCHBACK(BANK_SERIAL);
        return 1;
    }
    txBuffer[uart] = (uint8_t *)malloc(TX_BUFFER_SIZE);
    if (txBuffer[uart] == NULL) {
        free((void *)rxBuffer[uart]);
        MEMSWITCHBACK(BANK_SERIAL);
        return 1;
    }
    // Initialize state variables
    rxRead[uart] = 0;
    rxWrite[uart] = 0;
    txRead[uart] = 0;
    txWrite[uart] = 0;
    shouldStartTransmission[uart] = 1;
#ifdef FLOWCONTROL
    sendThisNext[uart] = 0;
    flow[uart] = 1;
    rxBufferElements[uart] = 0;
#endif
    // Default Configuration: 8N1
    *serialRegisters[uart][SERIALC] = (1 << serialBits[uart][SERIALUCSZ0]) | (1 << serialBits[uart][
      SERIALUCSZ1]);
    // Set baudrate
#if SERIALBAUDBIT == 8
    *serialRegisters[uart][SERIALUBRRH] = (baud >> 8);
    *serialRegisters[uart][SERIALUBRRL] = baud;
#else
    *serialBaudRegisters[uart] = baud;
#endif
    *serialRegisters[uart][SERIALB] = (1 << serialBits[uart][SERIALRXCIE]); // Enable Interrupts
    *serialRegisters[uart][SERIALB] |= (1 << serialBits[uart][SERIALRXEN]) | (1 << serialBits[uart][
      SERIALTXEN]); // Enable Receiver/Transmitter
    MEMSWITCHBACK(BANK_SERIAL);
    return 0;
}
uint8_t serialRxBufferEmpty (uint8_t uart)
Check if the receive buffer is empty.
Parameters
uart UART Module to check
Returns
1 if buffer is empty, 0 if not.
Definition at line 288 of file serial.c.
                                          {
    if (uart >= UART_COUNT)
        return 0;
    if (rxRead[uart] != rxWrite[uart]) {
        return 0;
    } else {
        return 1;
    }
}
uint8_t serialRxBufferFull (uint8_t uart)
Check if the receive buffer is full.
Parameters
uart UART Module to check
Returns
1 if buffer is full, 0 if not
Definition at line 281 of file serial.c.
References RX_BUFFER_SIZE.
                                         {
    if (uart >= UART_COUNT)
        return 0;
    return (((rxWrite[uart] + 1) == rxRead[uart]) || ((rxRead[uart] == 0) && ((rxWrite[uart] + 1) ==
      RX_BUFFER_SIZE)));
}
uint8_t serialTxBufferEmpty (uint8_t uart)
Check if the transmit buffer is empty.
Parameters
uart UART Module to check
Returns
1 if buffer is empty, 0 if not.
Definition at line 349 of file serial.c.
Referenced by serialClose().
                                          {
    if (uart >= UART_COUNT)
        return 0;
    if (txRead[uart] != txWrite[uart]) {
        return 0;
    } else {
        return 1;
    }
}
uint8_t serialTxBufferFull (uint8_t uart)
Check if the transmit buffer is full.
Parameters
uart UART Module to check
Returns
1 if buffer is full, 0 if not
Definition at line 342 of file serial.c.
References TX_BUFFER_SIZE.
Referenced by serialWrite().
                                         {
    if (uart >= UART_COUNT)
        return 0;
    return (((txWrite[uart] + 1) == txRead[uart]) || ((txRead[uart] == 0) && ((txWrite[uart] + 1) ==
      TX_BUFFER_SIZE)));
}
void serialWrite (uint8_t uart, uint8_t data)
Send a byte.
Parameters
uart UART Module to write to
data Byte to send
Definition at line 303 of file serial.c.
References BANK_SERIAL, MEMSWITCH, MEMSWITCHBACK, serialTxBufferFull(), and TX_BUFFER_SIZE.
Referenced by serialWriteString().
                                             {
    if (uart >= UART_COUNT)
        return;
    MEMSWITCH(BANK_SERIAL);
#ifdef SERIALINJECTCR
    if (data == '\n') {
        serialWrite(uart, '\r');
    }
#endif
    while (serialTxBufferFull(uart));
    txBuffer[uart][txWrite[uart]] = data;
    if (txWrite[uart] < (TX_BUFFER_SIZE - 1)) {
        txWrite[uart]++;
    } else {
        txWrite[uart] = 0;
    }
    if (shouldStartTransmission[uart]) {
        shouldStartTransmission[uart] = 0;
        *serialRegisters[uart][SERIALB] |= (1 << serialBits[uart][SERIALUDRIE]); // Enable Interrupt
        *serialRegisters[uart][SERIALA] |= (1 << serialBits[uart][SERIALUDRE]); // Trigger Interrupt
    }
    MEMSWITCHBACK(BANK_SERIAL);
}
void serialWriteString (uint8_t uart, const char * data)
Send a string.
Parameters
uart UART Module to write to
data Null-Terminated String
Definition at line 329 of file serial.c.
References serialWrite().
                                                       {
    if (uart >= UART_COUNT)
        return;
    if (data == 0) {
        serialWriteString(uart, "NULL");
    } else {
        while (*data != '\0') {
            serialWrite(uart, *data++);
        }
    }
}
void setFlow (uint8_t uart, uint8_t on)
Manually change the flow control.
Flow Control has to be compiled into the library!
Parameters
uart UART Module to operate on
on 1 of on, 0 if off
Definition at line 191 of file serial.c.
References XOFF, and XON.
                                       {
    if (uart >= UART_COUNT)
        return;
    if (flow[uart] != on) {
        if (on == 1) {
            // Send XON
            while (sendThisNext[uart] != 0);
            sendThisNext[uart] = XON;
            flow[uart] = 1;
            if (shouldStartTransmission[uart]) {
                shouldStartTransmission[uart] = 0;
                *serialRegisters[uart][SERIALB] |= (1 << serialBits[uart][SERIALUDRIE]);
                *serialRegisters[uart][SERIALA] |= (1 << serialBits[uart][SERIALUDRE]); // Trigger
       Interrupt
            }
        } else {
            // Send XOFF
            sendThisNext[uart] = XOFF;
            flow[uart] = 0;
            if (shouldStartTransmission[uart]) {
                shouldStartTransmission[uart] = 0;
                *serialRegisters[uart][SERIALB] |= (1 << serialBits[uart][SERIALUDRIE]);
                *serialRegisters[uart][SERIALA] |= (1 << serialBits[uart][SERIALUDRE]); // Trigger
       Interrupt
            }
        }
        // Wait till it's transmitted
        while (*serialRegisters[uart][SERIALB] & (1 << serialBits[uart][SERIALUDRIE]));
    }
}