I2C Driver
Using the AVR TWI/I2C Hardware.
Files
file twi.h
I2C API Header.
Macros
#define TWI_READ 1
I2C Read Bit.
#define TWI_WRITE 0
I2C Write Bit.
Functions
void twiInit (void)
Initialize the I2C Hardware.
void twiStop (void)
Stop the I2C Hardware.
unsigned char twiStart (unsigned char addr)
Start an I2C Transfer.
unsigned char twiRepStart (unsigned char addr)
Start a repeated I2C Transfer.
void twiStartWait (unsigned char addr)
Start an I2C Transfer and poll until ready.
unsigned char twiWrite (unsigned char data)
Write to the I2C Slave.
unsigned char twiReadAck (void)
Read from the I2C Slave and request more data.
unsigned char twiReadNak (void)
Read from the I2C Slave and deny more data.
Detailed Description
Using the AVR TWI/I2C Hardware.
Macro Definition Documentation
#define TWI_READ 1
I2C Read Bit.
Definition at line 43 of file twi.h.
Referenced by accRead(), gyroRead(), and magRead().
#define TWI_WRITE 0
I2C Write Bit.
Definition at line 44 of file twi.h.
Referenced by accRead(), gyroRead(), magRead(), magWriteRegister(), and motorTask().
Function Documentation
void twiInit (void)
Initialize the I2C Hardware.
Definition at line 26 of file twi.c.
Referenced by xyInit().
{
  /* initialize TWI clock: 100 kHz clock, TWPS = 0 => prescaler = 1 */
  TWSR = 0; /* no prescaler */
  TWBR = ((F_CPU/SCL_CLOCK)-16)/2; /* must be > 10 for stable operation */
}/* i2c_init */
unsigned char twiReadAck (void)
Read from the I2C Slave and request more data.
Returns
Data read
Definition at line 179 of file twi.c.
Referenced by accRead(), gyroRead(), and magRead().
{
    TWCR = (1<<TWINT) | (1<<TWEN) | (1<<TWEA);
    while(!(TWCR & (1<<TWINT)));
    return TWDR;
}/* i2c_readAck */
unsigned char twiReadNak (void)
Read from the I2C Slave and deny more data.
Returns
Data read
Definition at line 194 of file twi.c.
Referenced by accRead(), gyroRead(), and magRead().
{
    TWCR = (1<<TWINT) | (1<<TWEN);
    while(!(TWCR & (1<<TWINT)));
    return TWDR;
}/* i2c_readNak */
unsigned char twiRepStart (unsigned char addr)
Start a repeated I2C Transfer.
Parameters
addr Slave Address (with Read/Write bit)
Returns
0 on success, 1 on error
Definition at line 127 of file twi.c.
References twiStart().
Referenced by accRead(), gyroRead(), and magRead().
{
    return twiStart(address);
}/* i2c_rep_start */
unsigned char twiStart (unsigned char addr)
Start an I2C Transfer.
Parameters
addr Slave Address (with Read/Write bit)
Returns
0 on success, 1 on error
Definition at line 40 of file twi.c.
Referenced by accRead(), gyroRead(), magRead(), magWriteRegister(), motorTask(), and twiRepStart().
{
    uint8_t twst;
    // send START condition
    TWCR = (1<<TWINT) | (1<<TWSTA) | (1<<TWEN);
    // wait until transmission completed
    while(!(TWCR & (1<<TWINT)));
    // check value of TWI Status Register. Mask prescaler bits.
    twst = TW_STATUS & 0xF8;
    if ((twst != TW_START) && (twst != TW_REP_START)) return 1;
    // send device address
    TWDR = address;
    TWCR = (1<<TWINT) | (1<<TWEN);
    // wail until transmission completed and ACK/NACK has been received
    while(!(TWCR & (1<<TWINT)));
    // check value of TWI Status Register. Mask prescaler bits.
    twst = TW_STATUS & 0xF8;
    if ((twst != TW_MT_SLA_ACK) && (twst != TW_MR_SLA_ACK)) return 1;
    return 0;
}/* i2c_start */
void twiStartWait (unsigned char addr)
Start an I2C Transfer and poll until ready.
Parameters
addr Slave Address (with Read/Write bit)
Definition at line 76 of file twi.c.
{
    uint8_t twst;
    while (1)
    {
        // send START condition
        TWCR = (1<<TWINT) | (1<<TWSTA) | (1<<TWEN);
        // wait until transmission completed
        while(!(TWCR & (1<<TWINT)));
        // check value of TWI Status Register. Mask prescaler bits.
        twst = TW_STATUS & 0xF8;
        if ((twst != TW_START) && (twst != TW_REP_START)) continue;
        // send device address
        TWDR = address;
        TWCR = (1<<TWINT) | (1<<TWEN);
        // wail until transmission completed
        while(!(TWCR & (1<<TWINT)));
        // check value of TWI Status Register. Mask prescaler bits.
        twst = TW_STATUS & 0xF8;
        if ((twst == TW_MT_SLA_NACK)||(twst ==TW_MR_DATA_NACK))
        {
            /* device busy, send stop condition to terminate write operation */
            TWCR = (1<<TWINT) | (1<<TWEN) | (1<<TWSTO);
            // wait until stop condition is executed and bus released
            while(TWCR & (1<<TWSTO));
            continue;
        }
        //if(twst != TW_MT_SLA_ACK) return 1;
        break;
     }
}/* i2c_start_wait */
void twiStop (void)
Stop the I2C Hardware.
Definition at line 137 of file twi.c.
Referenced by magWriteRegister(), and motorTask().
{
    /* send stop condition */
    TWCR = (1<<TWINT) | (1<<TWEN) | (1<<TWSTO);
    // wait until stop condition is executed and bus released
    while(TWCR & (1<<TWSTO));
}/* i2c_stop */
unsigned char twiWrite (unsigned char data)
Write to the I2C Slave.
Parameters
data Data to send
Returns
0 on success, 1 on error
Definition at line 155 of file twi.c.
Referenced by accRead(), gyroRead(), magRead(), magWriteRegister(), and motorTask().
{
    uint8_t twst;
    // send data to the previously addressed device
    TWDR = data;
    TWCR = (1<<TWINT) | (1<<TWEN);
    // wait until transmission completed
    while(!(TWCR & (1<<TWINT)));
    // check value of TWI Status Register. Mask prescaler bits
    twst = TW_STATUS & 0xF8;
    if(twst != TW_MT_DATA_ACK) return 1;
    return 0;
}/* i2c_write */