UART Menu
Enables user interaction with an UART Menu.
Files
file uartMenu.h
UART Menu API Header.
file uartMenu.c
UART Menu API Implementation.
Data Structures
struct MenuEntry
Data Structure for Single-Linked-List for UART Menu.
Functions
uint8_t addMenuCommand (uint8_t cmd, PGM_P help, Task f)
Add a command to the UART Menu.
void uartMenuPrintHelp (void)
Print all registered commands.
void uartMenuRegisterHandler (void(*handler)(char))
Register a Handler for unhandled menu commands.
void uartMenuTask (void)
Task to work the UART Menu.
MenuEntry * findEntry (uint8_t cmd)
Search the uartMenu Linked List.
MenuEntry * reverseList (MenuEntry *root)
Reverse the UART Menu List.
Variables
MenuEntry * uartMenu = NULL
Single-Linked-List for commands.
void(* unHandler)(char) = NULL
Handler for unhandled commands.
Detailed Description
Enables user interaction with an UART Menu.
Function Documentation
uint8_t addMenuCommand (uint8_t cmd, PGM_P help, Task f)
Add a command to the UART Menu.
Parameters
cmd Byte that triggers command
help Help Text String in Flash
f Task to be executed
Returns
0 on success, 1 if already registered or not enough memory.
Examples:
hardwareTest.c, and uartFlight.c.
Definition at line 69 of file uartMenu.c.
References BANK_GENERIC, MenuEntry::cmd, MenuEntry::f, findEntry(), MenuEntry::helpText, MenuEntry::next, uartMenu, xmemGetBank(), and xmemSetBank().
Referenced by xyInit().
                                                        {
    uint8_t lastBank = xmemGetBank();
    xmemSetBank(BANK_GENERIC);
    if (findEntry(cmd) != NULL) {
        return 1;
    } else {
        MenuEntry *p = (MenuEntry *)malloc(sizeof(MenuEntry));
        if (p == NULL) {
            return 1;
        }
        p->cmd = cmd;
        p->helpText = help;
        p->f = f;
        p->next = uartMenu;
        uartMenu = p;
        return 0;
    }
    xmemSetBank(lastBank);
}
MenuEntry* findEntry (uint8_t cmd)
Search the uartMenu Linked List.
Parameters
cmd Command to search for
Returns
MenuEntry for command cmd, or NULL
Definition at line 58 of file uartMenu.c.
References MenuEntry::cmd, MenuEntry::next, and uartMenu.
Referenced by addMenuCommand().
                                  {
    MenuEntry *p = uartMenu;
    while (p != NULL) {
        if (p->cmd == cmd) {
            return p;
        }
        p = p->next;
    }
    return NULL;
}
MenuEntry* reverseList (MenuEntry * root)
Reverse the UART Menu List.
Parameters
root Root of the Single-Linked-List.
Returns
New root of reversed list.
Definition at line 93 of file uartMenu.c.
References MenuEntry::next.
Referenced by uartMenuPrintHelp().
                                        {
    MenuEntry *new = NULL;
    while (root != NULL) {
        MenuEntry *next = root->next;
        root->next = new;
        new = root;
        root = next;
    }
    return new;
}
void uartMenuPrintHelp (void)
Print all registered commands.
Definition at line 104 of file uartMenu.c.
References BANK_GENERIC, MenuEntry::cmd, MenuEntry::helpText, MenuEntry::next, reverseList(), uartMenu, xmemGetBank(), and xmemSetBank().
Referenced by xyInit().
                             {
    static uint8_t reversed = 0;
    uint8_t lastBank = xmemGetBank();
    xmemSetBank(BANK_GENERIC);
    char *buffer = (char *)malloc(35);
    if (buffer == NULL) {
        printf("!");
        return;
    }
    if (!reversed) {
        reversed = 1;
        uartMenu = reverseList(uartMenu);
    }
    MenuEntry *p = uartMenu;
    while (p != NULL) {
        strcpy_P(buffer, p->helpText);
        printf("%c: %s\n", p->cmd, buffer);
        p = p->next;
    }
    free(buffer);
    xmemSetBank(lastBank);
}
void uartMenuRegisterHandler (void(*)(char) handler)
Register a Handler for unhandled menu commands.
Parameters
handler Will be called if an unknown command is received.
Definition at line 127 of file uartMenu.c.
References unHandler.
                                                    {
    unHandler = handler;
}
void uartMenuTask (void)
Task to work the UART Menu.
Definition at line 131 of file uartMenu.c.
References BANK_GENERIC, MenuEntry::cmd, MenuEntry::f, MenuEntry::next, serialAvailable(), serialGet(), serialHasChar(), uartMenu, unHandler, xmemGetBank(), and xmemSetBank().
Referenced by xyInit().
                        {
    for (uint8_t i = 0; i < serialAvailable(); i++) {
        if (serialHasChar(i)) {
            uint8_t lastBank = xmemGetBank();
            xmemSetBank(BANK_GENERIC);
            uint8_t c = serialGet(i);
            MenuEntry *p = uartMenu;
            while (p != NULL) {
                if (p->cmd == c) {
                    p->f();
                    xmemSetBank(lastBank);
                    return;
                }
                p = p->next;
            }
            if (unHandler != NULL)
                unHandler(c);
            xmemSetBank(lastBank);
        }
    }
}
Variable Documentation
MenuEntry* uartMenu = NULL
Single-Linked-List for commands.
Definition at line 51 of file uartMenu.c.
Referenced by addMenuCommand(), findEntry(), uartMenuPrintHelp(), and uartMenuTask().
void(* unHandler)(char) = NULL
Handler for unhandled commands.
Definition at line 52 of file uartMenu.c.
Referenced by uartMenuRegisterHandler(), and uartMenuTask().