External Memory Interface
Allows access to external RAM with bank-switching.
Files
file xmem.h
XMEM API Header.
file xmem.c
XMEM API Implementation.
Data Structures
struct MallocState
All Malloc related State.
Macros
#define MEMSWITCH(x) uint8_t oldMemBank=xmemGetBank();if(oldMemBank!=x)xmemSetBank(x);
Switch the bank, if needed.
#define MEMSWITCHBACK(x) if(oldMemBank!=x)xmemSetBank(oldMemBank);
Switch back to the last bank, if needed.
#define MEMBANKS 8
Available Memory Banks.
#define BANK_GENERIC 0
Generic Memory Bank.
Functions
void xmemInit (void)
Initialize the External Memory Interface.
void xmemSetBank (uint8_t bank)
Switch the active memory bank.
uint8_t xmemGetBank (void)
Get the current memory bank.
void saveState (uint8_t bank)
Save the current malloc state.
void restoreState (uint8_t bank)
Restore the malloc state.
Variables
MallocState states [MEMBANKS]
MallocState for all Memory Banks.
uint8_t currentBank
Current active Memory Bank.
MallocState states [MEMBANKS]
MallocState for all Memory Banks.
uint8_t currentBank = 0
Current active Memory Bank.
void * __brkval
Internal Malloc Heap-End Pointer.
void * __flp
Internal Malloc Free List Pointer (State)
Detailed Description
Allows access to external RAM with bank-switching.
Macro Definition Documentation
#define BANK_GENERIC 0
Generic Memory Bank.
Definition at line 55 of file xmem.h.
Referenced by addMenuCommand(), addTask(), removeTask(), tasks(), tasksRegistered(), uartMenuPrintHelp(), and uartMenuTask().
#define MEMBANKS 8
Available Memory Banks.
Definition at line 54 of file xmem.h.
Referenced by xmemInit(), and xmemSetBank().
#define MEMSWITCH(x) uint8_t oldMemBank=xmemGetBank();if(oldMemBank!=x)xmemSetBank(x);
Switch the bank, if needed.
Stores the old bank in a variable oldMemBank.
Parameters
x New Bank
Definition at line 47 of file xmem.h.
Referenced by addTask(), removeTask(), tasks(), and tasksRegistered().
#define MEMSWITCHBACK(x) if(oldMemBank!=x)xmemSetBank(oldMemBank);
Switch back to the last bank, if needed.
Parameters
x New (current) Bank
Definition at line 52 of file xmem.h.
Referenced by addTask(), removeTask(), tasks(), and tasksRegistered().
Function Documentation
void restoreState (uint8_t bank)
Restore the malloc state.
Parameters
bank Location of state to load.
Definition at line 65 of file xmem.c.
References __brkval, __flp, MallocState::end, MallocState::fl, MallocState::start, and MallocState::val.
Referenced by xmemSetBank().
                                {
    __malloc_heap_start = states[bank].start;
    __malloc_heap_end = states[bank].end;
    __brkval = states[bank].val;
    __flp = states[bank].fl;
}
void saveState (uint8_t bank)
Save the current malloc state.
Parameters
bank Current Bank Number
Definition at line 55 of file xmem.c.
References __brkval, __flp, MallocState::end, MallocState::fl, MallocState::start, and MallocState::val.
Referenced by xmemInit(), and xmemSetBank().
                             {
    states[bank].start = __malloc_heap_start;
    states[bank].end = __malloc_heap_end;
    states[bank].val = __brkval;
    states[bank].fl = __flp;
}
uint8_t xmemGetBank (void)
Get the current memory bank.
Returns
Current Memory Bank.
Definition at line 105 of file xmem.c.
References currentBank.
Referenced by addMenuCommand(), uartMenuPrintHelp(), and uartMenuTask().
                          {
    return currentBank;
}
void xmemInit (void)
Initialize the External Memory Interface.
Definition at line 72 of file xmem.c.
References BANK0DDR, BANK0PIN, BANK0PORT, BANK1DDR, BANK1PIN, BANK1PORT, BANK2DDR, BANK2PIN, BANK2PORT, MEMBANKS, and saveState().
Referenced by xyInit().
                    {
    BANK0DDR |= (1 << BANK0PIN);
    BANK1DDR |= (1 << BANK1PIN);
    BANK2DDR |= (1 << BANK2PIN);
    BANK0PORT &= ~(1 << BANK0PIN);
    BANK1PORT &= ~(1 << BANK1PIN);
    BANK2PORT &= ~(1 << BANK2PIN);
    XMCRB = 0; // Use full address space
    XMCRA = (1 << SRW11) | (1 << SRW10); // 3 Wait cycles
    XMCRA |= (1 << SRE); // Enable XMEM
    for (uint8_t i = 0; i < MEMBANKS; i++) {
        saveState(i);
    }
}
void xmemSetBank (uint8_t bank)
Switch the active memory bank.
Parameters
bank New Memory Bank
Definition at line 89 of file xmem.c.
References BANK0PIN, BANK0PORT, BANK1PIN, BANK1PORT, BANK2PIN, BANK2PORT, currentBank, MEMBANKS, restoreState(), and saveState().
Referenced by addMenuCommand(), uartMenuPrintHelp(), and uartMenuTask().
                               {
    if (bank < MEMBANKS) {
        saveState(currentBank);
        BANK0PORT &= ~(1 << BANK0PIN);
        BANK1PORT &= ~(1 << BANK1PIN);
        BANK2PORT &= ~(1 << BANK2PIN);
        BANK0PORT |= ((bank & 0x01) << BANK0PIN);
        BANK1PORT |= (((bank & 0x02) >> 1) << BANK1PIN);
        BANK2PORT |= (((bank & 0x04) >> 2) << BANK2PIN);
        currentBank = bank;
        restoreState(bank);
    }
}
Variable Documentation
void* __brkval
Internal Malloc Heap-End Pointer.
Referenced by restoreState(), and saveState().
void* __flp
Internal Malloc Free List Pointer (State)
Referenced by restoreState(), and saveState().
uint8_t currentBank = 0
Current active Memory Bank.
Definition at line 47 of file xmem.c.
Referenced by xmemGetBank(), and xmemSetBank().
uint8_t currentBank
Current active Memory Bank.
Definition at line 47 of file xmem.c.
Referenced by xmemGetBank(), and xmemSetBank().
MallocState states[MEMBANKS]
MallocState for all Memory Banks.
Definition at line 46 of file xmem.c.
MallocState states[MEMBANKS]
MallocState for all Memory Banks.
Definition at line 46 of file xmem.c.