Magnetometer Driver
Configuring and reading an LSM303DLHC Magnetometer.
Files
file mag.h
LSM303DLHC Magnetometer API Header.
file mag.c
LSM303DLHC Magnetometer API Implementation.
Macros
#define MAGREG_CRB 0x01
Magnetometer Gain Register.
#define MAGREG_MR 0x02
Magnetometer Mode Register.
#define MAGREG_XH 0x03
First Magnetometer Output Register.
Enumerations
enum MagRange {
*
r1g3 = 1,
r1g9 = 2,
r2g5 = 3,
r4g0 = 4,
*
r4g7 = 5,
r5g6 = 6,
r8g1 = 7
 }
Magnetometer Range options.
Functions
Error magInit (MagRange r)
Initialize the Magnetometer.
Error magRead (Vector3f *v)
Read from the Magnetometer.
Error magWriteRegister (uint8_t reg, uint8_t val)
Write a Magnetometer Register.
Variables
MagRange magRange
Stored range to scale returned values.
Detailed Description
Configuring and reading an LSM303DLHC Magnetometer.
Macro Definition Documentation
#define MAGREG_CRB 0x01
Magnetometer Gain Register.
Definition at line 48 of file mag.c.
Referenced by magInit().
#define MAGREG_MR 0x02
Magnetometer Mode Register.
Definition at line 49 of file mag.c.
Referenced by magInit().
#define MAGREG_XH 0x03
First Magnetometer Output Register.
Definition at line 50 of file mag.c.
Referenced by magRead().
Enumeration Type Documentation
enum MagRange
Magnetometer Range options.
Enumerator
r1g3
 +- 1.3 Gauss
r1g9
 +- 1.9 Gauss
r2g5
 +- 2.5 Gauss
r4g0
 +- 4.0 Gauss
r4g7
 +- 4.7 Gauss
r5g6
 +- 5.6 Gauss
r8g1
 +- 8.1 Gauss
Definition at line 47 of file mag.h.
             {
    r1g3 = 1,
    r1g9 = 2,
    r2g5 = 3,
    r4g0 = 4,
    r4g7 = 5,
    r5g6 = 6,
    r8g1 = 7,
} MagRange;
Function Documentation
Error magInit (MagRange r)
Initialize the Magnetometer.
Call before magRead(). I2C should already be initialized!
Parameters
r MagRange to use.
Returns
TWI_NO_ANSWER, TWI_WRITE_ERROR, ARGUMENT_ERROR or SUCCESS.
Definition at line 75 of file mag.c.
References ARGUMENT_ERROR, magRange, MAGREG_CRB, MAGREG_MR, magWriteRegister(), and SUCCESS.
Referenced by orientationInit().
                          {
    if ((r <= 0) || (r >= 8)) {
        return ARGUMENT_ERROR;
    }
    Error e = magWriteRegister(MAGREG_MR, 0x00); // Continuous Conversion
    if (e != SUCCESS) {
        return e;
    }
    e = magWriteRegister(MAGREG_CRB, (r << 5)); // Set Range
    magRange = r;
    return e;
}
Error magRead (Vector3f * v)
Read from the Magnetometer.
Magnetometer should already be initialized!
Parameters
v Vector3f for the read values
Returns
TWI_NO_ANSWER, TWI_WRITE_ERROR, ARGUMENT_ERROR or SUCCESS.
Examples:
hardwareTest.c.
Definition at line 88 of file mag.c.
References ARGUMENT_ERROR, MAG_ADDRESS, magRange, MAGREG_XH, r1g3, r1g9, r2g5, r4g0, r4g7, r5g6, r8g1, SUCCESS, TWI_NO_ANSWER, TWI_READ, TWI_WRITE, TWI_WRITE_ERROR, twiReadAck(), twiReadNak(), twiRepStart(), twiStart(), twiWrite(), Vector3f::x, Vector3f::y, and Vector3f::z.
Referenced by orientationTask().
                           {
    if (v == NULL) {
        return ARGUMENT_ERROR;
    }
    if (twiStart(MAG_ADDRESS | TWI_WRITE)) {
        return TWI_NO_ANSWER;
    }
    if (twiWrite(MAGREG_XH)) {
        return TWI_WRITE_ERROR;
    }
    if (twiRepStart(MAG_ADDRESS | TWI_READ)) {
        return TWI_NO_ANSWER;
    }
    uint8_t xh = twiReadAck();
    uint8_t xl = twiReadAck();
    uint8_t zh = twiReadAck();
    uint8_t zl = twiReadAck();
    uint8_t yh = twiReadAck();
    uint8_t yl = twiReadNak();
    int16_t x = *(int8_t *)(&xh);
    x *= (1 << 8);
    x |= xl;
    int16_t y = *(int8_t *)(&yh);
    y *= (1 << 8);
    y |= yl;
    int16_t z = *(int8_t *)(&zh);
    z *= (1 << 8);
    z |= zl;
    switch (magRange) {
        case r1g3:
            v->x = (((double)x) * 1.3 / 0x8000);
            v->y = (((double)y) * 1.3 / 0x8000);
            v->z = (((double)z) * 1.3 / 0x8000);
            break;
        case r1g9:
            v->x = (((double)x) * 1.9 / 0x8000);
            v->y = (((double)y) * 1.9 / 0x8000);
            v->z = (((double)z) * 1.9 / 0x8000);
            break;
        case r2g5:
            v->x = (((double)x) * 2.5 / 0x8000);
            v->y = (((double)y) * 2.5 / 0x8000);
            v->z = (((double)z) * 2.5 / 0x8000);
            break;
        case r4g0:
            v->x = (((double)x) * 4.0 / 0x8000);
            v->y = (((double)y) * 4.0 / 0x8000);
            v->z = (((double)z) * 4.0 / 0x8000);
            break;
        case r4g7:
            v->x = (((double)x) * 4.7 / 0x8000);
            v->y = (((double)y) * 4.7 / 0x8000);
            v->z = (((double)z) * 4.7 / 0x8000);
            break;
        case r5g6:
            v->x = (((double)x) * 5.6 / 0x8000);
            v->y = (((double)y) * 5.6 / 0x8000);
            v->z = (((double)z) * 5.6 / 0x8000);
            break;
        case r8g1:
            v->x = (((double)x) * 8.1 / 0x8000);
            v->y = (((double)y) * 8.1 / 0x8000);
            v->z = (((double)z) * 8.1 / 0x8000);
            break;
        default:
            return ARGUMENT_ERROR;
    }
    return SUCCESS;
}
Error magWriteRegister (uint8_t reg, uint8_t val)
Write a Magnetometer Register.
I2C should aready be initialized!
Parameters
reg Register Address
val New Value
Returns
TWI_NO_ANSWER, TWI_WRITE_ERROR or SUCCESS.
Definition at line 61 of file mag.c.
References TWI_NO_ANSWER.
Referenced by magInit().
                                                 {
    if (twiStart(MAG_ADDRESS | TWI_WRITE)) {
        return TWI_NO_ANSWER;
    }
    if (twiWrite(reg)) {
        return TWI_WRITE_ERROR;
    }
    if (twiWrite(val)) {
        return TWI_WRITE_ERROR;
    }
    twiStop();
    return SUCCESS;
}
Variable Documentation
MagRange magRange
Stored range to scale returned values.
Definition at line 52 of file mag.c.
Referenced by magInit(), and magRead().