Motor Speed Mixer
Takes the Base Speed and PID-Output and sets Motor Speed accordingly.
Files
file set.h
Motor Mixer Library Header.
file set.c
Motor Mixer Library Implementation.
Macros
#define MAXDIFF (baseSpeed * PID_FACTOR)
Maximum Speed difference on one axis.
Functions
void setTask (void)
Read the PID Output and Set the Motor Speeds.
void setMotorSpeeds (uint8_t axis, uint8_t *vals)
Set the Motor Speeds according to the SET_* Motor Position Constants.
Variables
uint8_t baseSpeed
Motor Base Speed.
uint8_t baseSpeed = 0
Motor Base Speed.
Detailed Description
Takes the Base Speed and PID-Output and sets Motor Speed accordingly.
Macro Definition Documentation
#define MAXDIFF (baseSpeed * PID_FACTOR)
Maximum Speed difference on one axis.
Definition at line 51 of file set.c.
Referenced by setTask().
Function Documentation
void setMotorSpeeds (uint8_t axis, uint8_t * vals) [inline]
Set the Motor Speeds according to the SET_* Motor Position Constants.
Parameters
axis ROLL or PITCH
vals Speeds for the two Motors on this axis (+, -)
Definition at line 59 of file set.c.
References motorSet(), SET_ROLLMINUS, and SET_ROLLPLUS.
Referenced by setTask().
                                                        {
    if (axis == ROLL) {
        motorSet(SET_ROLLPLUS, vals[0]);
        motorSet(SET_ROLLMINUS, vals[1]);
    } else if (axis == PITCH) {
        motorSet(SET_PITCHPLUS, vals[0]);
        motorSet(SET_PITCHMINUS, vals[1]);
    }
}
void setTask (void)
Read the PID Output and Set the Motor Speeds.
Examples:
uartFlight.c.
Definition at line 69 of file set.c.
References baseSpeed, MAXDIFF, o_output, o_pids, and setMotorSpeeds().
                   {
    for (uint8_t i = 0; i < 2; i++) {
        double diff = (o_output[i] * MAXDIFF) / o_pids[i].outMax;
        uint8_t v[2] = { baseSpeed + diff, baseSpeed - diff };
        setMotorSpeeds(i, v);
    }
}
Variable Documentation
uint8_t baseSpeed
Motor Base Speed.
Examples:
uartFlight.c.
Definition at line 53 of file set.c.
Referenced by setTask().
uint8_t baseSpeed = 0
Motor Base Speed.
Definition at line 53 of file set.c.
Referenced by setTask().